### ISSUE TITLE
Judgments are invisible

### ISSUE THREAD

**Issue by adolfintel** [RhythmLunatic/Delta-NEX-Rebirth#29]
I'm using this theme on Stepmania 5.0.12, pump mode.
Maybe I'm an idiot but I can't seem to find a way to show judgments and the combo indicator. Is this a known issue or am I missing something?

Thanks

**Comment by kerti** [comment]
Same here, I got this dialog box too:

<img width="429" alt="screen shot 2018-08-30 at 17 04 25" src="https://user-images.githubusercontent.com/613032/44845123-e309f880-ac76-11e8-80a1-b330ff9fbadf.png">

**Comment by adolfintel** [comment]
Me too, I removed the extra files and it works but judgments are invisibile

On August 30, 2018 12:05:53 PM GMT+02:00, Raditya Kertiyasa <notifications@github.com> wrote:
>Same here, I got this dialog box too:
>
><img width="429" alt="screen shot 2018-08-30 at 17 04 25"
>src="https://user-images.githubusercontent.com/613032/44845123-e309f880-ac76-11e8-80a1-b330ff9fbadf.png">
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RhythmLunatic/Delta-NEX-Rebirth/issues/29#issuecomment-417265563

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RhythmLunatic** [comment]
Are you using 0.95?
If you aren't, going to Delta NEX settings and setting the judgement appearance will fix it.
If you are, then that should not happen and I'll try to find the cause of the issue.

Do not move the combo fonts, that's just StepMania being picky. I will fix it in the next commit.

**Comment by adolfintel** [comment]
That worked. Thank you!
