### ISSUE TITLE
How to select group?

### ISSUE THREAD

**Issue by alex-tee** [RhythmLunatic/Delta-NEX-Rebirth#34]
I'm looking for this everywhere but I can't figure out how to select a group. like 1:38 here: https://www.youtube.com/watch?v=vDLFMQm1xXQ

from this screen:

![Screenshot from 2021-11-26 16-11-44](https://user-images.githubusercontent.com/3407655/143607933-3a1d0625-1081-4f07-82f1-feb0f9eb5c1f.png)

Delta NEX Rebirth 0.95
StepMania 5.0.12

**Comment by alex-tee** [comment]
I found it: press up + down simultaneously

**Comment by RhythmLunatic** [comment]
This theme is not maintained, please try one of the forks or use Rave It Out.
