### ISSUE TITLE
cannot change difficulty in dance mode

### ISSUE THREAD

**Issue by camatthew** [RhythmLunatic/Delta-NEX-Rebirth#4]

**Comment by RhythmLunatic** [comment]
Please state your play mode (dance or pump) and version of StepMania.

**Comment by camatthew** [comment]
on both 5.0 and 5.1-3/5.1.0a3 versions. my  play mode is  dance

**Comment by RhythmLunatic** [comment]
This theme only supports 5.0.12 currently, 5.1 support is broken.

But anyway, it's broken. (and so is doubles, apparently.)

**Comment by camatthew** [comment]
diifficulty select doesent work on 5.0.12 on mac

**Comment by RhythmLunatic** [comment]
I fixed it, please download and replace metrics.ini

**Comment by camatthew** [comment]
still doesent work

**Comment by camatthew** [comment]
how do you change soung group

**Comment by camatthew** [comment]
worked
thanks

**Comment by camatthew** [comment]
please close issue
