### ISSUE TITLE
Secret Mode

### ISSUE THREAD

**Issue by RhythmLunatic** [RhythmLunatic/Delta-NEX-Rebirth#6]
Some sort of distinction between official PIU/DDR groups and user songs.

Currently the plan is that ↖↖↗↗↖↖↗↗ opens it. (Or ⬅⬅➡➡⬅⬅➡➡ for dance? Or ⬇⬆⬇⬆?)

**Comment by camatthew** [comment]
two top right arrows next to two top left arrows

**Comment by camatthew** [comment]
four up arrows for pump .up down left right for dance

**Comment by RhythmLunatic** [comment]
Added. https://github.com/RhythmLunatic/Delta-NEX-Rebirth/commit/76464dbe980216e3114120bb7464d6ee847fb856
